# Generated by Django 4.2.4 on 2023-08-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('num_reviews', models.PositiveIntegerField(default=0)),
                ('num_ratings', models.PositiveIntegerField(default=0)),
                ('ratings', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('num_media', models.PositiveIntegerField(default=0)),
                ('url', models.URLField()),
            ],
        ),
    ]
