# Generated by Django 4.2.4 on 2023-08-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scraper', '0003_alter_data_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
